### PR TITLE
Fix/edit button

### PR DESCRIPTION
**Pull request by skjnldsv**
- Move to async loading for better caching and quicker loading
``` bash
Hash: 5d6a207e2454698fcf14
Version: webpack 4.39.3
Time: 6250ms
Built at: 2019-08-29 9:05:51 AM
                                Asset      Size  Chunks             Chunk Names
    privacy.0.6b81ed84c571e0b443fa.js  14.2 KiB       0  [emitted]  
privacy.0.6b81ed84c571e0b443fa.js.map  64.1 KiB       0  [emitted]  
    privacy.1.06b18c3d51eed1bab07d.js   113 KiB       1  [emitted]  
privacy.1.06b18c3d51eed1bab07d.js.map   217 KiB       1  [emitted]  
    privacy.2.b5e18ac5edaafc9fe0ea.js   141 KiB       2  [emitted]  
privacy.2.b5e18ac5edaafc9fe0ea.js.map   279 KiB       2  [emitted]  
    privacy.4.8acd16eb51902a94e1b5.js  3.95 KiB       4  [emitted]  
privacy.4.8acd16eb51902a94e1b5.js.map  11.9 KiB       4  [emitted]  
    privacy.5.38ef4d292f450814823d.js  4.46 KiB       5  [emitted]  
privacy.5.38ef4d292f450814823d.js.map  11.6 KiB       5  [emitted]  
    privacy.6.fffa522f10bdbedc55b0.js   206 KiB       6  [emitted]  
privacy.6.fffa522f10bdbedc55b0.js.map   411 KiB       6  [emitted]  
    privacy.7.d1f54b6382fda5caa28d.js    68 KiB       7  [emitted]  
privacy.7.d1f54b6382fda5caa28d.js.map    96 KiB       7  [emitted]  
    privacy.8.4f0d99a3c05cad6d7a7a.js  1.41 KiB       8  [emitted]  
privacy.8.4f0d99a3c05cad6d7a7a.js.map  4.15 KiB       8  [emitted]  
                           privacy.js   156 KiB       3  [emitted]  main
                       privacy.js.map   775 KiB       3  [emitted]  main
Entrypoint main = privacy.js privacy.js.map

```
- Moved to using proper Actions components for better accessibility and benefit from future updates
Capture d’écran_2019-08-29_09-02-24
Capture d’écran_2019-08-29_09-02-33
Capture d’écran_2019-08-29_09-02-39

### CODE REVIEW

**Comment by skjnldsv** [comment]
@georgehrke this is not a rebasebot ^^

**Comment by georgehrke** [comment]
Damn :P 

Let me rebase manually then.

**Comment by georgehrke** [comment]
👍

**Pull request merged**
